import os
from datetime import datetime, timedelta
from typing import Optional
from cryptography.fernet import Fernet
from passlib.context import CryptContext
import jwt
from app.core.config import settings
from fastapi import Request, HTTPException
from jwt import PyJWKClient

# 1. AES Encryption for sensitive fields
try:
    _cipher_suite = Fernet(settings.ENCRYPTION_KEY.encode('utf-8'))
except ValueError:
    _cipher_suite = Fernet(Fernet.generate_key())

def encrypt_field(plaintext: str) -> str:
    if not plaintext:
        return ""
    return _cipher_suite.encrypt(plaintext.encode('utf-8')).decode('utf-8')

def decrypt_field(ciphertext: str) -> str:
    if not ciphertext:
        return ""
    try:
        return _cipher_suite.decrypt(ciphertext.encode('utf-8')).decode('utf-8')
    except Exception:
        return "Decryption Error"

# 2. Password Hashing
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def hash_password(password: str) -> str:
    return pwd_context.hash(password)

def verify_password(plain_password: str, hashed_password: str) -> bool:
    return pwd_context.verify(plain_password, hashed_password)

# 3. JWT Auth
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

def create_access_token(data: dict, expires_delta: Optional[timedelta] = None):
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, settings.JWT_SECRET, algorithm=ALGORITHM)
    return encoded_jwt

# 4. Firebase RS256 JWT Verification Setup
firebase_jwks_client = PyJWKClient("https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com")

def verify_firebase_token(token: str) -> dict:
    """Verifies RS256 signature of a Firebase/Google token using public keys."""
    try:
        signing_key = firebase_jwks_client.get_signing_key_from_jwt(token)
        # We skip audience verification for this hackathon as we don't have the fixed Firebase Project ID in backend env
        payload = jwt.decode(token, signing_key.key, algorithms=["RS256"], options={"verify_aud": False})
        return payload
    except Exception as e:
        print(f"Token Verification Failed: {e}")
        return None

# 5. Admin Authentication Guard
def get_current_admin(request: Request):
    """Verifies that the caller is an authenticated Admin."""
    auth_header = request.headers.get("Authorization")
    if not auth_header or not auth_header.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Unauthorized - Missing Admin Token")
    
    token = auth_header.split(" ")[1]
    try:
        # Admin tokens are generated by our backend (HS256)
        payload = jwt.decode(token, settings.JWT_SECRET, algorithms=[ALGORITHM])
        username = payload.get("sub")
        if not username:
            raise HTTPException(status_code=401, detail="Invalid token")
        return username
    except jwt.ExpiredSignatureError:
        raise HTTPException(status_code=401, detail="Admin token expired")
    except Exception:
        raise HTTPException(status_code=401, detail="Invalid admin token")
